<?php
class pariksa_controller extends base_controller {

	public function __construct() {
		parent::__construct();
	} 


	public function p_init_game(){


		//add this info to the incoming psot
		$_POST['user_id']=$this->user->user_id;
		$_POST['date_play']=Time::now();

		//send data above and content to the DB
		DB::instance(DB_NAME)->insert('scores',$_POST);

		//route the user back to the profile page
		Router::redirect('/pariksa/game');

	}


	public function game($score_id = NULL) {

		// set up the views
		$this->template->content = View::instance('v_pariksa_game');
		$this->template->title = "Game";
		$this->template->content->score_id = $score_id;

		// render the view
		echo $this->template;

	}


	public function p_cont_game($score_id = NULL){


		//accept the information from the field
		$new_vyanjana = $_POST['vyanjana'];
		$new_date_play =Time::now();

		//set incoming data as an array
		$scoredata = Array('vyanjana'=>$new_vyanjana,'date_play'=>$new_date_play,);

		//use sql to update the DB with the information stored in the array above
		DB::instance(DB_NAME)->update('scores',$scoredata,'Where score_id ='.$score_id);

		//route the user back to the profile page
		Router::redirect('/pariksa/game');

	}

	public function p_quit_game(){


		//create a var to store data generated by following
		$where_condition = 'WHERE score_id = '.$score_id;

		//delete where this condition is met
		DB::instance(DB_NAME)->delete('scores',$where_condition);

		//route the user back to the profile page
		Router::redirect('/');
		

	}

} 










} # end of the class